   
    export const copy = {
      pt: {
        navExplore: "Explorar", navMine: "Meus Anúncios", navWish: "Wish List", navMessages: "Mensagens", navHow: "Como funciona", navAbout: "Sobre",
        hero1: "Swap more", hero2: "Keep your cash", heroSub: "Turn what you have into what you want — without spending", dream: "Realiza os teus sonhos a custo 0 ✦", explore: "Explorar ofertas", publish: "Publicar anúncio",
        searchTitle: "O que você procura?", have: "Eu tenho", want: "Procuro", distance: "Até", matches: "Encontros para si", trust: "Confiança que se conquista", premium: "troCASH PREMIUM",
        trustLong: "A confiança nasce de regras claras, perfis verificados e boas experiências.",
        slogan2: "More swapping. Less spending.",
        trustBadge1Title: "Seguro",
        trustBadge1Sub: "Verificado",
        trustBadge2Title: "Comunidade",
        trustBadge2Sub: "Confiável",
        trustBadge3Title: "Sustentável",
        trustBadge3Sub: "Consciente",
        trustBadge4Title: "Local",
        trustBadge4Sub: "Algarve",
        verificationTitle: "Verificação de membros",
        verificationSub: "Mais segurança para todos.",
        noMoneyTitle: "Sem dinheiro entre membros",
        noMoneySub: "Troca valor por valor.",
        supportTitle: "Suporte dedicado",
        supportSub: "Ajuda quando precisares.",
        privacyTitle: "Privacidade",
        privacySub: "Os teus dados protegidos.",
        premiumHeading: "Mais oportunidades. Menos esforço.",
        premiumSub: "Destaca as tuas ofertas, encontra correspondências mais depressa e navega sem distrações.",
        viewAll: "Ver todas →",
        searchButton: "Pesquisar",
        smartMatches: "Smart Matches: a pesquisar trocas compatíveis para {have} → {want}.",
        wishlistAria: "Lista de deseos",
        premiumPriceLabel: "€4,99 / mês",
        premiumButton: "Quero Premium",
        premiumModalHeading: "Mais trocas. Menos gastos.",
        premiumModalBody: "O preço de €4,99/mês foi desenhado para ser simples e transparente. A ligação ao pagamento será ativada quando o checkout estiver ligado ao teu MB WAY.",
        premiumModalList: "Ofertas destacadas|Correspondências prioritárias|Sem publicidade|Suporte prioritário",
        footerBrandline: "JUNTOS CRIAMOS VALOR.",
        footerLine1: "Swap more. Keep your cash.",
        footerLine2: "Realiza os teus sonhos a custo 0.",
        footerLine3: "Exchange more. Spend less. Live more.",
        footerTroCASH: "troCASH",
        footerAbout: "Sobre nós",
        footerHow: "Como funciona",
        footerRules: "Regras da comunidade",
        footerSupportTitle: "Suporte",
        footerSupportHelp: "Centro de ajuda",
        footerSupportSecurity: "Segurança",
        footerSupportPrivacy: "Privacidade",
        footerCommunityTitle: "Comunidade",
        footerCommunityItems: "Sustentabilidade|Dicas e artigos|Eventos locais",
        footerNewsTitle: "Recebe novidades",
        footerNewsSub: "Ideias para trocar melhor, gastar menos e viver mais."
      },
      en: {
        navExplore: "Explore", navMine: "My Listings", navWish: "Wish List", navMessages: "Messages", navHow: "How it works", navAbout: "About",
        hero1: "Swap more", hero2: "Keep your cash", heroSub: "Turn what you have into what you want — without spending", dream: "Make your dreams happen at zero cost ✦", explore: "Explore offers", publish: "Post an offer",
        searchTitle: "What are you looking for?", have: "I have", want: "I want", distance: "Within", matches: "Matches for you", trust: "Trust is earned", premium: "troCASH PREMIUM",
        trustLong: "Trust grows from clear rules, verified profiles and good experiences.",
        slogan2: "More swapping. Less spending.",
        trustBadge1Title: "Safe",
        trustBadge1Sub: "Verified",
        trustBadge2Title: "Community",
        trustBadge2Sub: "Trusted",
        trustBadge3Title: "Sustainable",
        trustBadge3Sub: "Conscious",
        trustBadge4Title: "Local",
        trustBadge4Sub: "Algarve",
        verificationTitle: "Member verification",
        verificationSub: "More safety for everyone.",
        noMoneyTitle: "No money between members",
        noMoneySub: "Trade value for value.",
        supportTitle: "Dedicated support",
        supportSub: "Help when you need it.",
        privacyTitle: "Privacy",
        privacySub: "Your data is protected.",
        premiumHeading: "More opportunities. Less effort.",
        premiumSub: "Highlight your offers, find matches faster, and browse distraction-free.",
        premiumPriceLabel: "€4.99 / month",
        premiumButton: "Get Premium",
        searchButton: "Search",
        viewAll: "View all →",
        smartMatches: "Smart Matches: searching compatible swaps for {have} → {want}.",
        wishlistAria: "Wishlist",
        premiumModalHeading: "More swaps. Less spending.",
        premiumModalBody: "The €4.99/month price is designed to be simple and transparent. Payment will be enabled when checkout is connected to your payment method.",
        premiumModalList: "Featured offers|Priority matches|No ads|Priority support",
        footerBrandline: "TOGETHER WE CREATE VALUE.",
        footerLine1: "Swap more. Keep your cash.",
        footerLine2: "Make your dreams happen at zero cost.",
        footerLine3: "Exchange more. Spend less. Live more.",
        footerTroCASH: "troCASH",
        footerAbout: "About us",
        footerHow: "How it works",
        footerRules: "Community rules",
        footerSupportTitle: "Support",
        footerSupportHelp: "Help center",
        footerSupportSecurity: "Security",
        footerSupportPrivacy: "Privacy",
        footerCommunityTitle: "Community",
        footerCommunityItems: "Sustainability|Tips & articles|Local events",
        footerNewsTitle: "Get updates",
        footerNewsSub: "Ideas to swap better, spend less and live more."
      },

      fr: {
        navExplore: "Explorer", navMine: "Mes annonces", navWish: "Liste de souhaits", navMessages: "Messages", navHow: "Comment ça marche", navAbout: "À propos",
        hero1: "Échangez plus", hero2: "Gardez votre argent", heroSub: "Transformez ce que vous avez en ce que vous voulez — sans dépenser", dream: "Réalisez vos rêves à zéro coût ✦", explore: "Explorer les offres", publish: "Publier une annonce",
        searchTitle: "Que recherchez-vous?", have: "J'ai", want: "Je veux", distance: "Dans un rayon de", matches: "Correspondances pour vous", trust: "La confiance se mérite", premium: "troCASH PREMIUM",
        trustLong: "La confiance naît de règles claires, de profils vérifiés et de bonnes expériences.",
        slogan2: "Plus d'échanges. Moins de dépenses.",
        trustBadge1Title: "Sûr", trustBadge1Sub: "Vérifié",
        trustBadge2Title: "Communauté", trustBadge2Sub: "Fiable",
        trustBadge3Title: "Durable", trustBadge3Sub: "Responsable",
        trustBadge4Title: "Local", trustBadge4Sub: "Algarve",
        verificationTitle: "Vérification des membres", verificationSub: "Plus de sécurité pour tous.",
        noMoneyTitle: "Pas d'argent entre membres", noMoneySub: "Échange valeur contre valeur.",
        supportTitle: "Support dédié", supportSub: "Aide quand vous en avez besoin.",
        privacyTitle: "Confidentialité", privacySub: "Vos données sont protégées.",
        premiumHeading: "Plus d'opportunités. Moins d'effort.",
        premiumSub: "Mettez en avant vos offres, trouvez des correspondances plus vite et naviguez sans distractions.",
        viewAll: "Voir tout →", searchButton: "Rechercher",
        smartMatches: "Smart Matches : recherche d'échanges compatibles pour {have} → {want}.",
        wishlistAria: "Liste de souhaits",
        premiumPriceLabel: "4,99 € / mois",
        premiumButton: "Obtenir Premium",
        premiumModalHeading: "Plus d'échanges. Moins de dépenses.",
        premiumModalBody: "Le prix de 4,99 €/mois est conçu pour être simple et transparent. Le paiement sera activé lorsque le checkout sera connecté à votre méthode de paiement.",
        premiumModalList: "Offres en vedette|Correspondances prioritaires|Sans publicité|Support prioritaire",
        footerBrandline: "ENSEMBLE NOUS CRÉONS DE LA VALEUR.",
        footerLine1: "Échangez plus. Gardez votre argent.",
        footerLine2: "Réalisez vos rêves à coût zéro.",
        footerLine3: "Échangez plus. Dépensez moins. Vivez mieux.",
        footerTroCASH: "troCASH",
        footerAbout: "À propos de nous", footerHow: "Comment ça marche", footerRules: "Règles de la communauté",
        footerSupportTitle: "Support", footerSupportHelp: "Centre d'aide", footerSupportSecurity: "Sécurité", footerSupportPrivacy: "Confidentialité",
        footerCommunityTitle: "Communauté", footerCommunityItems: "Durabilité|Conseils & articles|Événements locaux",
        footerNewsTitle: "Recevoir les nouveautés", footerNewsSub: "Idées pour échanger mieux, dépenser moins et vivre plus."
      },

      it: {
        navExplore: "Esplora", navMine: "I miei annunci", navWish: "Lista dei desideri", navMessages: "Messaggi", navHow: "Come funziona", navAbout: "Chi siamo",
        hero1: "Scambia di più", hero2: "Tieni i tuoi soldi", heroSub: "Trasforma ciò che hai in ciò che desideri — senza spendere", dream: "Realizza i tuoi sogni a costo zero ✦", explore: "Esplora offerte", publish: "Pubblica annuncio",
        searchTitle: "Cosa stai cercando?", have: "Ho", want: "Voglio", distance: "Entro", matches: "Risultati per te", trust: "La fiducia si guadagna", premium: "troCASH PREMIUM",
        trustLong: "La fiducia cresce da regole chiare, profili verificati e buone esperienze.",
        slogan2: "Più scambi. Meno spese.",
        trustBadge1Title: "Sicuro", trustBadge1Sub: "Verificato",
        trustBadge2Title: "Comunità", trustBadge2Sub: "Affidabile",
        trustBadge3Title: "Sostenibile", trustBadge3Sub: "Consapevole",
        trustBadge4Title: "Locale", trustBadge4Sub: "Algarve",
        verificationTitle: "Verifica dei membri", verificationSub: "Più sicurezza per tutti.",
        noMoneyTitle: "Niente soldi tra membri", noMoneySub: "Scambia valore per valore.",
        supportTitle: "Supporto dedicato", supportSub: "Aiuto quando ne hai bisogno.",
        privacyTitle: "Privacy", privacySub: "I tuoi dati sono protetti.",
        premiumHeading: "Più opportunità. Meno fatica.",
        premiumSub: "Metti in evidenza le tue offerte, trova corrispondenze più velocemente e naviga senza distrazioni.",
        viewAll: "Vedi tutto →", searchButton: "Cerca",
        smartMatches: "Smart Matches: ricerca scambi compatibili per {have} → {want}.",
        wishlistAria: "Lista dei desideri",
        premiumPriceLabel: "€4,99 / mese",
        premiumButton: "Voglio Premium",
        premiumModalHeading: "Più scambi. Meno spese.",
        premiumModalBody: "Il prezzo di €4,99/mese è pensato per essere semplice e trasparente. Il pagamento sarà abilitato quando il checkout sarà connesso al tuo metodo di pagamento.",
        premiumModalList: "Offerte in evidenza|Corrispondenze prioritarie|Senza pubblicità|Supporto prioritario",
        footerBrandline: "INSIEME CREIAMO VALORE.",
        footerLine1: "Scambia di più. Tieni i tuoi soldi.",
        footerLine2: "Realizza i tuoi sogni a costo zero.",
        footerLine3: "Scambia di più. Spendi meno. Vivi di più.",
        footerTroCASH: "troCASH",
        footerAbout: "Chi siamo", footerHow: "Come funziona", footerRules: "Regole della community",
        footerSupportTitle: "Supporto", footerSupportHelp: "Centro assistenza", footerSupportSecurity: "Sicurezza", footerSupportPrivacy: "Privacy",
        footerCommunityTitle: "Community", footerCommunityItems: "Sostenibilità|Consigli & articoli|Eventi locali",
        footerNewsTitle: "Ricevi aggiornamenti", footerNewsSub: "Idee per scambiare meglio, spendere meno e vivere di più."
      },

      es: {
        navExplore: "Explorar", navMine: "Mis anuncios", navWish: "Lista de deseos", navMessages: "Mensajes", navHow: "Cómo funciona", navAbout: "Sobre nosotros",
        hero1: "Intercambia más", hero2: "Mantén tu dinero", heroSub: "Convierte lo que tienes en lo que quieres — sin gastar", dream: "Haz tus sueños realidad a costo cero ✦", explore: "Explorar ofertas", publish: "Publicar oferta",
        searchTitle: "¿Qué estás buscando?", have: "Tengo", want: "Quiero", distance: "Dentro de", matches: "Coincidencias para ti", trust: "La confianza se gana", premium: "troCASH PREMIUM",
        trustLong: "La confianza nace de reglas claras, perfiles verificados y buenas experiencias.",
        slogan2: "Más intercambio. Menos gasto.",
        trustBadge1Title: "Seguro", trustBadge1Sub: "Verificado",
        trustBadge2Title: "Comunidad", trustBadge2Sub: "Confiable",
        trustBadge3Title: "Sostenible", trustBadge3Sub: "Consciente",
        trustBadge4Title: "Local", trustBadge4Sub: "Algarve",
        verificationTitle: "Verificación de miembros", verificationSub: "Más seguridad para todos.",
        noMoneyTitle: "Sin dinero entre miembros", noMoneySub: "Intercambia valor por valor.",
        supportTitle: "Soporte dedicado", supportSub: "Ayuda cuando la necesites.",
        privacyTitle: "Privacidad", privacySub: "Tus datos están protegidos.",
        premiumHeading: "Más oportunidades. Menos esfuerzo.",
        premiumSub: "Destaca tus ofertas, encuentra coincidancias más rápido y navega sin distracciones.",
        viewAll: "Ver todo →", searchButton: "Buscar",
        smartMatches: "Smart Matches: buscando intercambios compatibles para {have} → {want}.",
        wishlistAria: "Lista de deseos",
        premiumPriceLabel: "€4,99 / mes",
        premiumButton: "Quiero Premium",
        premiumModalHeading: "Más intercambios. Menos gastos.",
        premiumModalBody: "El precio de €4,99/mes está diseñado para ser simple y transparente. El pago se activará cuando el checkout esté conectado a tu método de pago.",
        premiumModalList: "Ofertas destacadas|Coincidencias prioritarias|Sin publicidad|Soporte prioritario",
        footerBrandline: "JUNTOS CREAMOS VALOR.",
        footerLine1: "Intercambia más. Mantén tu dinero.",
        footerLine2: "Haz realidad tus sueños a costo cero.",
        footerLine3: "Intercambia más. Gasta menos. Vive más.",
        footerTroCASH: "troCASH",
        footerAbout: "Sobre nosotros", footerHow: "Cómo funciona", footerRules: "Reglas de la comunidad",
        footerSupportTitle: "Soporte", footerSupportHelp: "Centro de ayuda", footerSupportSecurity: "Seguridad", footerSupportPrivacy: "Privacidad",
        footerCommunityTitle: "Comunidad", footerCommunityItems: "Sostenibilidad|Consejos y artículos|Eventos locales",
        footerNewsTitle: "Recibe novedades", footerNewsSub: "Ideas para intercambiar mejor, gastar menos y vivir más."
      },

      de: {
        navExplore: "Entdecken", navMine: "Meine Anzeigen", navWish: "Wunschliste", navMessages: "Nachrichten", navHow: "Wie es funktioniert", navAbout: "Über uns",
        hero1: "Mehr tauschen", hero2: "Behalte dein Geld", heroSub: "Verwandle, was du hast, in das, was du willst — ohne zu bezahlen", dream: "Erfülle deine Träume ohne Kosten ✦", explore: "Angebote entdecken", publish: "Angebot veröffentlichen",
        searchTitle: "Wonach suchst du?", have: "Ich habe", want: "Ich möchte", distance: "Innerhalb von", matches: "Treffer für dich", trust: "Vertrauen wird verdient", premium: "troCASH PREMIUM",
        trustLong: "Vertrauen entsteht durch klare Regeln, verifizierte Profile und gute Erfahrungen.",
        slogan2: "Mehr Tausch. Weniger Ausgaben.",
        trustBadge1Title: "Sicher", trustBadge1Sub: "Verifiziert",
        trustBadge2Title: "Gemeinschaft", trustBadge2Sub: "Vertrauenswürdig",
        trustBadge3Title: "Nachhaltig", trustBadge3Sub: "Bewusst",
        trustBadge4Title: "Lokal", trustBadge4Sub: "Algarve",
        verificationTitle: "Mitglieder-Verifizierung", verificationSub: "Mehr Sicherheit für alle.",
        noMoneyTitle: "Kein Geld zwischen Mitgliedern", noMoneySub: "Tausche Wert gegen Wert.",
        supportTitle: "Dedicated Support", supportSub: "Hilfe, wenn du sie brauchst.",
        privacyTitle: "Datenschutz", privacySub: "Deine Daten sind geschützt.",
        premiumHeading: "Mehr Chancen. Weniger Aufwand.",
        premiumSub: "Hebe deine Angebote hervor, finde schneller passende Treffer und surfe ohne Ablenkung.",
        viewAll: "Alle ansehen →", searchButton: "Suchen",
        smartMatches: "Smart Matches: Suche nach passenden Tauschpartnern für {have} → {want}.",
        wishlistAria: "Wunschliste",
        premiumPriceLabel: "€4,99 / Monat",
        premiumButton: "Premium holen",
        premiumModalHeading: "Mehr Tausch. Weniger Ausgaben.",
        premiumModalBody: "Der Preis von €4,99/Monat ist einfach und transparent gestaltet. Die Zahlung wird aktiviert, wenn der Checkout mit deiner Zahlungsmethode verbunden ist.",
        premiumModalList: "Empfohlene Angebote|Prioritäre Treffer|Keine Werbung|Priorisierter Support",
        footerBrandline: "ZUSAMMEN SCHAFFEN WIR WERT.",
        footerLine1: "Mehr tauschen. Behalte dein Geld.",
        footerLine2: "Erfülle deine Träume ohne Kosten.",
        footerLine3: "Tausche mehr. Gib weniger aus. Lebe mehr.",
        footerTroCASH: "troCASH",
        footerAbout: "Über uns", footerHow: "Wie es funktioniert", footerRules: "Community-Regeln",
        footerSupportTitle: "Support", footerSupportHelp: "Hilfe-Center", footerSupportSecurity: "Sicherheit", footerSupportPrivacy: "Datenschutz",
        footerCommunityTitle: "Community", footerCommunityItems: "Nachhaltigkeit|Tipps & Artikel|Lokale Events",
        footerNewsTitle: "Neuigkeiten erhalten", footerNewsSub: "Ideen, um besser zu tauschen, weniger auszugeben und mehr zu erleben."
      },

      uk: {
        navExplore: "Дослідити", navMine: "Мої оголошення", navWish: "Список бажань", navMessages: "Повідомлення", navHow: "Як це працює", navAbout: "Про нас",
        hero1: "Більше обмінів", hero2: "Збережи свої гроші", heroSub: "Перетвори те, що маєш, на те, що хочеш — без витрат", dream: "Здійсни свої мрії безкоштовно ✦", explore: "Переглянути пропозиції", publish: "Опублікувати оголошення",
        searchTitle: "Що ви шукаєте?", have: "У мене є", want: "Я хочу", distance: "У радіусі", matches: "Підібрано для вас", trust: "Довіра заробляється", premium: "troCASH PREMIUM",
        trustLong: "Довіра з'являється завдяки чітким правилам, верифікованим профілям і хорошому досвіду.",
        slogan2: "Більше обміну. Менше витрат.",
        trustBadge1Title: "Безпечно", trustBadge1Sub: "Перевірено",
        trustBadge2Title: "Спільнота", trustBadge2Sub: "Надійно",
        trustBadge3Title: "Стійко", trustBadge3Sub: "Свідомо",
        trustBadge4Title: "Локально", trustBadge4Sub: "Algarve",
        verificationTitle: "Перевірка учасників", verificationSub: "Більше безпеки для всіх.",
        noMoneyTitle: "Жодних грошей між учасниками", noMoneySub: "Обмін значеннями за значення.",
        supportTitle: "Підтримка", supportSub: "Допомога, коли потрібно.",
        privacyTitle: "Конфіденційність", privacySub: "Ваші дані під захистом.",
        premiumHeading: "Більше можливостей. Менше зусиль.",
        premiumSub: "Видіть свої пропозиції, знаходьте збіги швидше і переглядайте без відволікань.",
        viewAll: "Показати всі →", searchButton: "Пошук",
        smartMatches: "Smart Matches: шукаємо сумісні обміни для {have} → {want}.",
        wishlistAria: "Список бажань",
        premiumPriceLabel: "€4,99 / місяць",
        premiumButton: "Хочу Premium",
        premiumModalHeading: "Більше обмінів. Менше витрат.",
        premiumModalBody: "Ціна €4,99/місяць зроблена простою і прозорою. Оплата буде доступна після підключення способу оплати.",
        premiumModalList: "Виділені пропозиції|Пріоритетні збіги|Без реклами|Пріоритетна підтримка",
        footerBrandline: "РАЗОМ МИ ТВОРИМО ЦІННІСТЬ.",
        footerLine1: "Більше обміну. Збережи свої гроші.",
        footerLine2: "Здійсни свої мрії безкоштовно.",
        footerLine3: "Обмінюй більше. Трать менше. Живи краще.",
        footerTroCASH: "troCASH",
        footerAbout: "Про нас", footerHow: "Як це працює", footerRules: "Правила спільноти",
        footerSupportTitle: "Підтримка", footerSupportHelp: "Центр допомоги", footerSupportSecurity: "Безпека", footerSupportPrivacy: "Приватність",
        footerCommunityTitle: "Спільнота", footerCommunityItems: "Стійкість|Поради та статті|Місцеві події",
        footerNewsTitle: "Отримувати новини", footerNewsSub: "Ідеї, як краще обмінюватись, менше витрачати та більше жити."
      },

      zh: {
        navExplore: "探索", navMine: "我的发布", navWish: "愿望清单", navMessages: "消息", navHow: "如何运作", navAbout: "关于我们",
        hero1: "更多交换", hero2: "保留你的现金", heroSub: "把你拥有的变成你想要的 — 无需花钱", dream: "以零成本实现你的梦想 ✦", explore: "探索商品", publish: "发布商品",
        searchTitle: "你在寻找什么？", have: "我有", want: "我想要", distance: "范围内", matches: "为你匹配", trust: "信任需要赢得", premium: "troCASH 高级版",
        trustLong: "信任源于明确的规则、已验证的个人资料和良好体验。",
        slogan2: "更多交换。更少消费。",
        trustBadge1Title: "安全", trustBadge1Sub: "已验证",
        trustBadge2Title: "社区", trustBadge2Sub: "可信赖",
        trustBadge3Title: "可持续", trustBadge3Sub: "有意识",
        trustBadge4Title: "本地", trustBadge4Sub: "阿尔加维",
        verificationTitle: "成员验证", verificationSub: "为所有人提供更多安全性。",
        noMoneyTitle: "成员之间无需金钱", noMoneySub: "以物换物，等价交换。",
        supportTitle: "专属支持", supportSub: "需要时提供帮助。",
        privacyTitle: "隐私", privacySub: "保护你的数据。",
        premiumHeading: "更多机会。更少努力。",
        premiumSub: "突出你的商品，更快找到匹配，无广告浏览。",
        viewAll: "查看全部 →", searchButton: "搜索",
        smartMatches: "智能匹配：正在为 {have} → {want} 寻找兼容的交换。",
        wishlistAria: "愿望清单",
        premiumPriceLabel: "€4.99 / 月",
        premiumButton: "获取高级版",
        premiumModalHeading: "更多交换。更少花费。",
        premiumModalBody: "每月 €4.99 的定价简单透明。结账连接到你的支付方式后将启用支付功能。",
        premiumModalList: "精选商品|优先匹配|无广告|优先支持",
        footerBrandline: "我们一起创造价值。",
        footerLine1: "更多交换。保留你的现金。",
        footerLine2: "以零成本实现你的梦想。",
        footerLine3: "多交换。少花费。多生活。",
        footerTroCASH: "troCASH",
        footerAbout: "关于我们", footerHow: "如何运作", footerRules: "社区规则",
        footerSupportTitle: "支持", footerSupportHelp: "帮助中心", footerSupportSecurity: "安全", footerSupportPrivacy: "隐私",
        footerCommunityTitle: "社区", footerCommunityItems: "可持续性|技巧与文章|本地活动",
        footerNewsTitle: "获取更新", footerNewsSub: "关于更好交换、少花钱和更多生活的想法。"
      },

      ru: {
        navExplore: "Исследовать", navMine: "Мои объявления", navWish: "Список желаний", navMessages: "Сообщения", navHow: "Как это работает", navAbout: "О нас",
        hero1: "Обменивайтесь больше", hero2: "Сохраняйте деньги", heroSub: "Преобразуйте то, что у вас есть, в то, что вы хотите — без затрат", dream: "Осуществляйте мечты без расходов ✦", explore: "Просмотреть предложения", publish: "Опубликовать объявление",
        searchTitle: "Что вы ищете?", have: "У меня есть", want: "Я хочу", distance: "В пределах", matches: "Совпадения для вас", trust: "Доверие заслуживается", premium: "troCASH ПРЕМИУМ",
        trustLong: "Доверие строится на понятных правилах, проверенных профилях и хорошем опыте.",
        slogan2: "Больше обменов. Меньше трат.",
        trustBadge1Title: "Безопасно", trustBadge1Sub: "Проверено",
        trustBadge2Title: "Сообщество", trustBadge2Sub: "Надёжно",
        trustBadge3Title: "Устойчиво", trustBadge3Sub: "Осознанно",
        trustBadge4Title: "Локально", trustBadge4Sub: "Algarve",
        verificationTitle: "Проверка участников", verificationSub: "Больше безопасности для всех.",
        noMoneyTitle: "Без денег между участниками", noMoneySub: "Обмен стоимостью на стоимость.",
        supportTitle: "Поддержка", supportSub: "Помощь, когда нужно.",
        privacyTitle: "Конфиденциальность", privacySub: "Ваши данные защищены.",
        premiumHeading: "Больше возможностей. Меньше усилий.",
        premiumSub: "Выделяйте свои объявления, находите совпадения быстрее и просматривайте без отвлечений.",
        viewAll: "Показать все →", searchButton: "Поиск",
        smartMatches: "Smart Matches: поиск совместимых обменов для {have} → {want}.",
        wishlistAria: "Список желаний",
        premiumPriceLabel: "€4,99 / месяц",
        premiumButton: "Получить Premium",
        premiumModalHeading: "Больше обменов. Меньше расходов.",
        premiumModalBody: "Цена €4,99/месяц разработана, чтобы быть простой и прозрачной. Оплата будет активирована после подключения способа оплаты.",
        premiumModalList: "Рекомендованные предложения|Приоритетные совпадения|Без рекламы|Приоритетная поддержка",
        footerBrandline: "ВМЕСТЕ МЫ СОЗДАЁМ ЦЕННОСТЬ.",
        footerLine1: "Больше обменов. Сохраняйте деньги.",
        footerLine2: "Осуществляйте мечты без затрат.",
        footerLine3: "Обменивайте больше. Тратьте меньше. Живите больше.",
        footerTroCASH: "troCASH",
        footerAbout: "О нас", footerHow: "Как это работает", footerRules: "Правила сообщества",
        footerSupportTitle: "Поддержка", footerSupportHelp: "Центр помощи", footerSupportSecurity: "Безопасность", footerSupportPrivacy: "Конфиденциальность",
        footerCommunityTitle: "Сообщество", footerCommunityItems: "Устойчивость|Советы и статьи|Местные мероприятия",
        footerNewsTitle: "Получать обновления", footerNewsSub: "Идеи, как лучше обмениваться, тратить меньше и жить больше."
      }
    };

    export const LANGUAGES = [
      { code: "pt", flag: "🇵🇹", label: "Português" },
      { code: "en", flag: "🇬🇧", label: "English" },
      { code: "fr", flag: "🇫🇷", label: "Français" },
      { code: "it", flag: "🇮🇹", label: "Italiano" },
      { code: "es", flag: "🇪🇸", label: "Español" },
      { code: "de", flag: "🇩🇪", label: "Deutsch" },
      { code: "uk", flag: "🇺🇦", label: "Українська" },
      { code: "zh", flag: "🇨🇳", label: "中文" },
      { code: "ru", flag: "🇷🇺", label: "Русский" }
    ];
export default { copy };