   
    export const copy = {
      pt: {
        navExplore: "Explorar", navMine: "Meus Anúncios", navWish: "Wish List", navMessages: "Mensagens", navHow: "Como funciona", navAbout: "Sobre",
        hero1: "Troque mais", hero2: "Guarde o seu dinheiro", heroSub: "Transforme o que tem no que deseja — sem gastar", dream: "Realiza os teus sonhos a custo 0 ✦", explore: "Explorar ofertas", publish: "Publicar anúncio",
        searchTitle: "O que você procura?",searchSub: "Encontra uma troca que faça sentido para ti",category: "Categoria", have: "Eu tenho", want: "O que", distance: "Até", matches: "Encontros para si", trust: "Confiança que se conquista", premium: "troCASH PREMIUM",
        searchOfferTitle: "O que você oferece?",
        offerSub: "Veja os itens ou serviços que você oferece",
        offerWishPlaceholder: "Ex.: sofá, câmara, outro serviço...",
          trustLong: "A confiança nasce de regras claras, perfis verificados e boas experiências",
        slogan2: "Mais trocas. Menos gastos.",
        trustBadge1Title: "Seguro",
        trustBadge1Sub: "Verificado",
        trustBadge2Title: "Comunidade",
        trustBadge2Sub: "Confiável",
        trustBadge3Title: "Sustentável",
        trustBadge3Sub: "Consciente",
        trustBadge4Title: "Local",
        trustBadge4Sub: "Algarve",
        verificationTitle: "Verificação de membros",
        verificationSub: "Mais segurança para todos.",
        noMoneyTitle: "Sem dinheiro entre membros",
        noMoneySub: "Troca valor por valor.",
        supportTitle: "Suporte dedicado",        
        supportSub: "Ajuda quando precisares.",    
        privacyTitle: "Privacidade",
        privacySub: "Os teus dados protegidos.",
        premiumHeading: "Mais oportunidades. Menos esforço.",
        premiumSub: "Destaca as tuas ofertas, encontra correspondências mais depressa e navega sem distrações.",
        viewAll: "Ver todas →",
        searchButton: "Pesquisar",
        smartMatches: "Smart Matches: a pesquisar trocas compatíveis para {have} → {want}.",
        wishlistAria: "Lista de deseos",
        premiumPriceLabel: "€4,99 / mês",
        premiumButton: "Quero Premium",
        premiumModalHeading: "Mais trocas. Menos gastos.",
        premiumModalBody: "O preço de €4,99/mês foi desenhado para ser simples e transparente. A ligação ao pagamento será ativada quando o checkout estiver ligado ao teu MB WAY.",
        premiumModalList: "Ofertas destacadas|Correspondências prioritárias|Sem publicidade|Suporte prioritário",
        footerBrandline: "JUNTOS CRIAMOS VALOR.",
        footerLine1: "Troque para poupar, troque pelo planeta.",
        footerLine2: "Realiza os teus sonhos a custo 0.",
        footerLine3: "Troque mais. Gaste menos. Viva mais.",
        footerTroCASH: "troCASH",
        footerAbout: "Sobre nós",
        footerHow: "Como funciona",
        footerRules: "Regras da comunidade",
        footerSupportTitle: "Suporte",
        footerSupportHelp: "Centro de ajuda",
        footerSupportSecurity: "Segurança",
        footerSupportPrivacy: "Privacidade",
        footerCommunityTitle: "Comunidade",
        footerCommunityItems: "Sustentabilidade|Dicas e artigos|Eventos locais",
        footerNewsTitle: "Recebe novidades",
        footerNewsSub: "Ideias para trocar melhor, gastar menos e viver mais.",
        selectCategory: "Selecione uma categoria",
        categories: {
          Todas: "Todas",
          Casa: "Casa",
          Moda: "Moda",
          Eletrónica: "Eletrónica",
          Livros: "Livros",
          Desporto: "Desporto",
          Serviços: "Serviços",
          Tempo: "Tempo",
          Outros: "Outros"
        }
      },
      en: {
        navExplore: "Explore", navMine: "My Listings", navWish: "Wish List", navMessages: "Messages", navHow: "How it works", navAbout: "About",
        hero1: "Swap more", hero2: "Keep your cash", heroSub: "Turn what you have into what you want — without spending", dream: "Make your dreams happen at zero cost ✦", explore: "Explore offers", publish: "Post an offer",
        searchTitle: "What are you looking for?",searchSub: "Find a swap that makes sense for you",category: "Category", have: "I have", want: "What", distance: "Within", matches: "Matches for you", trust: "Trust is earned", premium: "troCASH PREMIUM",
        searchOfferTitle: "What do you offer?",
        offerSub: "Browse items or services you offer",
        offerWishPlaceholder: "E.g.: sofa, camera, another service...",
          trustLong: "Trust grows from clear rules, verified profiles and good experiences",
        slogan2: "More swapping. Less spending.",
        trustBadge1Title: "Safe",
        trustBadge1Sub: "Verified",
        trustBadge2Title: "Community",
        trustBadge2Sub: "Trusted",
        trustBadge3Title: "Sustainable",
        trustBadge3Sub: "Conscious",
        trustBadge4Title: "Local",
        trustBadge4Sub: "Algarve",
        verificationTitle: "Member verification",
        verificationSub: "More safety for everyone.",
        noMoneyTitle: "No money between members",
        noMoneySub: "Trade value for value.",
        supportTitle: "Dedicated support",
        supportSub: "Help when you need it.",
        privacyTitle: "Privacy",
        privacySub: "Your data is protected.",
        premiumHeading: "More opportunities. Less effort.",
        premiumSub: "Highlight your offers, find matches faster, and browse distraction-free.",
        premiumPriceLabel: "€4.99 / month",
        premiumButton: "Get Premium",
        searchButton: "Search",
        viewAll: "View all →",
        smartMatches: "Smart Matches: searching compatible swaps for {have} → {want}.",
        wishlistAria: "Wishlist",
        premiumModalHeading: "More swaps. Less spending.",
        premiumModalBody: "The €4.99/month price is designed to be simple and transparent. Payment will be enabled when checkout is connected to your payment method.",
        premiumModalList: "Featured offers|Priority matches|No ads|Priority support",
        footerBrandline: "TOGETHER WE CREATE VALUE.",
        footerLine1: "Swap more. Keep your cash.",
        footerLine2: "Make your dreams happen at zero cost.",
        footerLine3: "Exchange more. Spend less. Live more.",
        footerTroCASH: "troCASH",
        footerAbout: "About us",
        footerHow: "How it works",
        footerRules: "Community rules",
        footerSupportTitle: "Support",
        footerSupportHelp: "Help center",
        footerSupportSecurity: "Security",
        footerSupportPrivacy: "Privacy",
        footerCommunityTitle: "Community",
        footerCommunityItems: "Sustainability|Tips & articles|Local events",
        footerNewsTitle: "Get updates",
        footerNewsSub: "Ideas to swap better, spend less and live more.",
        selectCategory: "Select a category",
        categories: {
          Todas: "All",
          Casa: "Home",
          Moda: "Fashion",
          Eletrónica: "Electronics",
          Livros: "Books",
          Desporto: "Sport",
          Serviços: "Services",
          Tempo: "Time",
          Outros: "Other"
        }
      },
      uk: {
        navExplore: "Дослідити", navMine: "Мої оголошення", navWish: "Список бажань", navMessages: "Повідомлення", navHow: "Як це працює", navAbout: "Про нас",
        hero1: "Більше обмінів", hero2: "Збережи свої гроші", heroSub: "Перетвори те, що маєш, на те, що хочеш — без витрат", dream: "Здійсни свої мрії безкоштовно ✦", explore: "Переглянути пропозиції", publish: "Опублікувати оголошення",
        searchTitle: "Що ви шукаєте?",searchSub: "Знайди речі, які будуть тобі корисні",category: "Категорія", have: "Пропоную", want: "Що", distance: "У радіусі", matches: "Підібрано для вас", trust: "Довіра заробляється", premium: "troCASH PREMIUM",
        searchOfferTitle: "Що ви пропонуєте?",
        offerSub: "Перегляньте речі чи послуги, які пропонуєте",
        offerWishPlaceholder: "Наприклад: диван, камера, інша послуга...",
          trustLong: "Довіра з'являється завдяки чітким правилам, верифікованим профілям і хорошому досвіду.",
        slogan2: "Більше обміну. Менше витрат.",
        trustBadge1Title: "Безпечно", trustBadge1Sub: "Перевірено",
        trustBadge2Title: "Спільнота", trustBadge2Sub: "Надійно",
        trustBadge3Title: "Стійко", trustBadge3Sub: "Свідомо",
        trustBadge4Title: "Локально", trustBadge4Sub: "Algarve",
        verificationTitle: "Перевірка учасників", verificationSub: "Більше безпеки для всіх.",
        noMoneyTitle: "Жодних грошей між учасниками", noMoneySub: "Обмін значеннями за значення.",
        supportTitle: "Підтримка", supportSub: "Допомога, коли потрібно.",
        privacyTitle: "Конфіденційність", privacySub: "Ваші дані під захистом.",
        premiumHeading: "Більше можливостей. Менше зусиль.",
        premiumSub: "Видіть свої пропозиції, знаходьте збіги швидше і переглядайте без відволікань.",
        viewAll: "Показати всі →", searchButton: "Пошук",
        smartMatches: "Smart Matches: шукаємо сумісні обміни для {have} → {want}.",
        wishlistAria: "Список бажань",
        premiumPriceLabel: "€4,99 / місяць",
        premiumButton: "Хочу Premium",
        premiumModalHeading: "Більше обмінів. Менше витрат.",
        premiumModalBody: "Ціна €4,99/місяць зроблена простою і прозорою. Оплата буде доступна після підключення способу оплати.",
        premiumModalList: "Виділені пропозиції|Пріоритетні збіги|Без реклами|Пріоритетна підтримка",
        footerBrandline: "РАЗОМ МИ ТВОРИМО ЦІННІСТЬ.",
        footerLine1: "Більше обміну. Збережи свої гроші.",
        footerLine2: "Здійсни свої мрії безкоштовно.",
        footerLine3: "Обмінюй більше. Трать менше. Живи краще.",
        footerTroCASH: "troCASH",
        footerAbout: "Про нас", footerHow: "Як це працює", footerRules: "Правила спільноти",
        footerSupportTitle: "Підтримка", footerSupportHelp: "Центр допомоги", footerSupportSecurity: "Безпека", footerSupportPrivacy: "Приватність",
        footerCommunityTitle: "Спільнота", footerCommunityItems: "Стійкість|Поради та статті|Місцеві події",
        footerNewsTitle: "Отримувати новини", footerNewsSub: "Ідеї, як краще обмінюватись, менше витрачати та більше жити.",
        selectCategory: "Оберіть категорію",
        categories: {
          Todas: "Усі",
          Casa: "Дім",
          Moda: "Мода",
          Eletrónica: "Електроніка",
          Livros: "Книги",
          Desporto: "Спорт",
          Serviços: "Послуги",
          Tempo: "Час",
          Outros: "Інше"
        }
      }

    };

    export const LANGUAGES = [
      { code: "pt", flag: "🇵🇹", label: "Português" },
      { code: "en", flag: "🇬🇧", label: "English" },
      { code: "uk", flag: "🇺🇦", label: "Українська" },      
    ];
export default { copy };